[commandDescriptions]
  about      = "Information about the bot"
  choose     = "Picks from a selection menu"
  discordfm  = "Plays music from discord.fm playlists"
  dump       = "Outputs the music queue as a json string"
  help       = "Shows command help"
  invite     = "Adds the bot to your server"
  jump       = "Skips to a time in the current song"
  move       = "Moves the bot to a different voice channel"
  nowplaying = "Shows the current song"
  pause      = "Pauses & resumes the song"
  play       = "Adds a song to the queue and begins playing"
  queue      = "Shows the song queue"
  radio      = "Streams UK radio stations"
  reorder    = "Changes the position of a song in the queue"
  repeat     = "Loops the current song"
  restart    = "Plays a song from the beginning"
  search     = "Searches for a song on youtube"
  shuffle    = "Shuffles the song queue"
  skip       = "Plays the next song in the queue"
  stop       = "Stops playing and leaves the voice channel"
  volume     = "Changes the music volume"

[radioStations]
  "KissFM"                = "http://icy-e-ba-09-boh.sharp-stream.com/kissnational.mp3"
  "CapitalFM"             = "http://media-ice.musicradio.com/CapitalSouthWalesMP3"
  "Heart"                 = "http://media-ice.musicradio.com/HeartSouthWalesMP3"
  "Absolute Radio"        = "http://icy-e-bab-09-boh.sharp-stream.com/absoluteradio.mp3"
  "ClassicalFM"           = "http://media-ice.musicradio.com/ClassicFMMP3"
  "Smooth Radio"          = "http://media-ice.musicradio.com/SmoothSouthWalesMP3"
  "The Breeze"            = "http://stream5.radiomonitor.com/Breeze-Bristol-128"
  "PowerFM"               = "http://icast.powergroup.com.tr/PowerFM/mpeg/128/home"
  "BBC Radio 1"           = "http://www.listenlive.eu/bbcradio1.m3u"
  "BBC Radio 2"           = "http://www.listenlive.eu/bbcradio2.m3u"
  "BBC Radio 3"           = "http://www.listenlive.eu/bbcradio3.m3u"
  "BBC Radio 4"           = "http://www.listenlive.eu/bbcradio4.m3u"
  "BBC Radio 5 Live"      = "http://www.listenlive.eu/bbc5live.m3u"
  "BBC 1Xtra"             = "http://www.listenlive.eu/bbc1xtra.m3u"
  "BBC Asian Network"     = "http://www.listenlive.eu/bbcasian.m3u"
  "GGRadio.net"           = "http://sv.ggradio.net:8000/stream"
  "Hive365"               = "http://stream.hive365.co.uk:8088/live"
  "Happy Christmas Radio" = "http://streaming.radionomy.com/HappyChristmasradio"
  "Los40"                 = "http://19113.live.streamtheworld.com/LOS40.mp3"
  "M-1"                   = "http://stream.m-1.fm/M-1aacp"
  "PowerHitRadio"         = "http://power-stream.data.lt:8000/PHR.mp3"
  "TheWave"               = "http://gbradio.cdn.tibus.net/SWAWave"
  "SwanseaSound"          = "http://gbradio.cdn.tibus.net/SWASS"
  "NRK mP3"               = "http://nrk-mms-live.online.no/nrk_radio_mp3_aac_h"
  "BridgeFM"              = "http://icy-e-03-boh.sharp-stream.com/tcbridge.mp3"
  "Cima 100"              = "http://www.surfmusic.de/m3u/cima-100-fm,3447.m3u"
  "Radio Disney"          = "http://radio.domint.net:8026/"